---
apiVersion: v1
kind: Namespace
metadata:
  name: mastodon-server

---
apiVersion: v1
kind: Secret
metadata:
  namespace: mastodon-server
  name: backup-secret
type: Opaque
stringData:
  S3_ACCESS_KEY_ID: <CHANGE-ME>
  S3_SECRET_ACCESS_KEY: <CHANGE-ME>
  S3_BUCKET: <CHANGE-ME>
  S3_ENDPOINT: <CHANGE-ME>


---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgresql-backup-cron-job
  namespace: mastodon-server
spec: 
  schedule: "0 */12 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: postgresql-backup-job
            image: ghcr.io/zaherg/postgres_backup:latest
            imagePullPolicy: Always
            env:
            - name: POSTGRES_DATABASE
              value: "all"
            - name: POSTGRES_HOST
              value: "postgres.mastodon-server"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db_secrets
                  key: POSTGRES_USER              
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db_secrets
                  key: POSTGRES_USER
            - name: S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: backup_secrets
                  key: S3_ACCESS_KEY_ID   
            - name: S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: db_sbackup_secretsecrets
                  key: S3_SECRET_ACCESS_KEY   
            - name: S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: backup_secrets
                  key: S3_BUCKET   
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: backup_secrets
                  key: S3_ENDPOINT   
          restartPolicy: OnFailure
          volumes:
            - name: db_secrets
              secret:
                secretName: postgres-secret
            - name: backup_secrets
              secret:
                secretName: backup-secret

      backoffLimit: 3