---
apiVersion: v1
kind: Namespace
metadata:
  name: mastodon-server

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: mastodon-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: mastodon-server
spec:
  selector:
    app: redis
  ports:
    - name: redis-port
      protocol: TCP
      port: 6379

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: mastodon-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        name: redis
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-2
      containers:
        - name: redis
          image: redis:latest
          imagePullPolicy: Always
          args: ["--appendonly", "yes"]
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - name: redis-storage
              mountPath: /data
          env:
              - name: ALLOW_EMPTY_PASSWORD
                value: "yes"
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc

